# Generated by Django 3.2.5 on 2021-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210811_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
