# Generated by Django 3.2.6 on 2021-08-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Category', 'verbose_name_plural': 'Sub-Categories'},
        ),
    ]
