# Generated by Django 3.2.6 on 2021-08-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210811_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default="From dress-down Fridays to weekend 'fits, our edit of men’s polo shirts knows no bounds when it comes to versatility. From long-sleeve polo shirts to short-sleeve polo tops, Wellbos DESIGN has hundreds of styles and designs to suit your unique style, or take your pick from men's designer polo shirts by Fred Perry and Polo Ralph Lauren, adding their classic logos to your smart-casual rotation. You can pair your polo T-shirt with skinny jeans, tailored shorts or even check trousers. Preppy vibes incoming."),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
