# Generated by Django 3.2.6 on 2021-08-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210811_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='desc',
            field=models.CharField(default='Trustworthy threads', max_length=30),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/category/sub'),
        ),
    ]
